DROP TABLE;
DROP VIEW;
DROP TRIGGER;

CREATE TABLE IF NOT EXISTS DrinkingWaterServiceArea (
	PWSID	TEXT NOT NULL,
	County	TEXT,
	State	TEXT,
	PopulationServed	INTEGER,
	PRIMARY KEY(PWSID)
);

CREATE TABLE IF NOT EXISTS LocationPolygon (
	PWSID	TEXT NOT NULL,
	Latitude	INTEGER,
	Longitude	INTEGER,
	PRIMARY KEY(PWSID,Latitude,Longitude),
	FOREIGN KEY(PWSID) REFERENCES Drinking Water Service Area(PWSID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PrimaryCountyServed (
	County	TEXT,
	State	TEXT,
	PWSID	TEXT NOT NULL,
	CountyFIPSCode	INTEGER,
	Municipality	TEXT,
	PRIMARY KEY(PWSID, County, State),
	FOREIGN KEY(PWSID) REFERENCES DrinkingWaterServiceArea(PWSID) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS CensusReport (
	PWSID	TEXT,
	County	TEXT,
	State	TEXT,
	Year	INTEGER,
	EnvJusticeCriteria	TEXT,
	EJBlockGroups	TEXT,
	TotalBlockGroups	TEXT,
	PrecentEJBlockGroups	INTEGER,
	EJBGPopulation	INTEGER,
	Population	INTEGER,
	PercentEJBGPopulation	INTEGER,
	FIPSCode	INTEGER,
	PWSID	INTEGER,
	FOREIGN KEY(PWSID) REFERENCES PrimaryCountyServed (PWSID),
	PRIMARY KEY(Year, PWSID, COUNTY, State)
);

CREATE TABLE IF NOT EXISTS Surveyed (
	PWSID	TEXT,
	County	TEXT,
	State	TEXT,
	YEAR	INTEGER,
	FOREIGN KEY( YEAR ) REFERENCES CensusReport(Year) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY( PWSID ) REFERENCES PrimaryCountyServed( PWSID ) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(County) REFERENCES PrimaryCountyServed (County) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(State) REFERENCES PrimaryCountyServed (State) ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY(PWSID, County, State, YEAR)
);


CREATE TABLE IF NOT EXISTS Violation (
	PWSID	INTEGER NOT NULL,
	ViolationID	INTEGER NOT NULL,
	Year INTEGER,
	Quarter	INTEGER,
	Type	TEXT,
	PRIMARY KEY(ViolationID,PWSID),
	FOREIGN KEY(PWSID) REFERENCES DrinkingWaterServiceArea (PWSID) ON UPDATE CASCADE ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS UtilityViolation (
	UDate	Date,
	Time	TEXT,
	Quality	TEXT,
	ViolationID	INTEGER NOT NULL,
	PRIMARY KEY(ViolationID)
	FOREIGN KEY(ViolationID)REFERENCES Violation (ViolationID)
);



CREATE TABLE IF NOT EXISTS PointViolation (
	VDate	TEXT,
	Time	TEXT,
	Latitude	INTEGER,
	Longitude	INTEGER,
	Quality	TEXT,
	ViolationID	INTEGER NOT NULL,
	PointType	TEXT,
	PWSID	TEXT NOT NULL,
	PRIMARY KEY(PWSID,ViolationID),
	FOREIGN KEY(ViolationID) REFERENCES Violation (ViolationID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS EPAViolation (
	PWSID		INTEGER,
	ViolationID		INTEGER,
	Quality		TEXT,
	FOREIGN KEY(PWSID) REFERENCES DrinkingWaterServiceArea,
	PRIMARY KEY(Violation ID, PWSID)
);

CREATE TABLE IF NOT EXISTS HealthReport (
	CASEID	INTEGER NOT NULL,
	PWSID	TEXT,
	Name	TEXT,
	Address	TEXT,
	OnsetDate	TEXT,
	EndDate	TEXT,
	Symptoms	TEXT,
	Hospitalized	TEXT,
	LabResults	TEXT,
	PRIMARY KEY(CASEID),
	FOREIGN KEY(PWSID) REFERENCES DrinkingWaterServiceArea(PWSID) ON UPDATE cascade ON DELETE cascade
);


